### ISSUE TITLE
Доработка профиля пользователя

### ISSUE THREAD

**Issue by alexbaumgertner** [AnnaApk/my-interviews#12]
отобразить имя и написать запросы для записи/изменения остальных полей
https://github.com/AnnaApk/my-interviews/pull/10#issuecomment-2112480653

**Comment by AnnaApk** [comment]
@alexbaumgertner 
не заметила сразу, что авторизация на верселе не работает
https://my-interviews-indol.vercel.app/api/auth/error
посмотрела логи, как написано на странице авторизации, ошибка ниже

добавила в Environment Variables : GITHUB_SECRET/ID, GOOGLE_SECRET/ID, NEXTAUTH_SECRET
но пока что-то не заработало 


[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. r [MissingSecretError]: Please define a `secret` in production.
    at t.assertConfig (/var/task/.next/server/app/api/auth/[...nextauth]/route.js:59:110934)
    at _ (/var/task/.next/server/app/api/auth/[...nextauth]/route.js:59:104298)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async a (/var/task/.next/server/app/api/auth/[...nextauth]/route.js:83:19583)
    at async e.length.t (/var/task/.next/server/app/api/auth/[...nextauth]/route.js:83:20994)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41960 {
  code: 'NO_SECRET'
}

**Comment by AnnaApk** [comment]
вторая трудность с которой я столкнулась

не меняла в аторизации ничего в последнем коммите, но она почему-то перестала работать 
запрос никуда не уходит
пока не понимаю в чем дело

**Comment by alexbaumgertner** [comment]
Ок, Посмотрю завтра.

**Comment by alexbaumgertner** [comment]
@AnnaApk Ты в Vercel деплоишь? 

Покажи пожалуйста, как у тебя выглядит /settings/environment-variables

<img width="981" alt="Screenshot 2024-05-22 at 17 45 42" src="https://github.com/AnnaApk/my-interviews/assets/223620/ef9cd8e8-7e8c-4045-b9ed-bcc8c0e4bd17">

**Comment by AnnaApk** [comment]
<img width="992" alt="image" src="https://github.com/AnnaApk/my-interviews/assets/94643227/36b5e245-b689-4919-9bea-83063b355b57">
<img width="953" alt="image" src="https://github.com/AnnaApk/my-interviews/assets/94643227/5256ec07-05c8-45d8-a6b7-ab5db91c80a9">

**Comment by AnnaApk** [comment]
@alexbaumgertner 
c  продакшеном все поправила 
https://my-interviews-indol.vercel.app/
должна авторизация работать


проблема локально осталась, но кажется  проблема в том, что остался процесс какой-то на localhoct:3000,  и проект запускается на 3001
а вроде как в nextauth по умолчанию 3000 для режима-разработки, как можно прервать чтобы не было запущено на конкретном сервере локально?

**Comment by alexbaumgertner** [comment]
> @alexbaumgertner c продакшеном все поправила https://my-interviews-indol.vercel.app/ должна авторизация работать
> 

Супер! А в чем была проблема?

> проблема локально осталась, но кажется проблема в том, что остался процесс какой-то на localhoct:3000, и проект запускается на 3001 а вроде как в nextauth по умолчанию 3000 для режима-разработки, как можно прервать чтобы не было запущено на конкретном сервере локально?

Да, 3000 порт по умолчанию. Посмотреть какой процесс занял порт можно так (если не путаю команды):


### Windows
```
netstat -ano | findstr :<номер порта>
```

### MacOS/Linux
```
 lsof -i :<номер порта>
```
— команды покажут ID процесса.

И завершить процесс через `kill ID`.

**Comment by alexbaumgertner** [comment]
Пробую менять поля (в safari) — не сохраняется. Когда нажимаю "редактировать ФИО" — показывается пустой инпут.

<img width="574" alt="Screenshot 2024-05-28 at 17 36 08" src="https://github.com/AnnaApk/my-interviews/assets/223620/283e6e37-0d50-479b-991e-39f24f167856">


<img width="323" alt="Screenshot 2024-05-28 at 17 36 45" src="https://github.com/AnnaApk/my-interviews/assets/223620/7923a7e8-86d2-4d34-bc51-a16665dbbb82">

**Comment by AnnaApk** [comment]
> Супер! А в чем была проблема?

 по большей части в моей невнимательности, после добавления переменных нужно было пересобрать прооект,
и я не вспомнила, что в провайдерах в проектах (гитхабе и гугле) нужно добавить urlы продакшена


> И завершить процесс через `kill ID`.

Да, убила процесс, перезапустила, теперь и локально все вернулось в норму

**Comment by AnnaApk** [comment]
@alexbaumgertner 
замержила
а стала проверять, и оказалось сломала что-то сегодня в 'experience'
разберусь и поправлю

**Comment by AnnaApk** [comment]
@alexbaumgertner 
поправила
можно смотреть
https://my-interviews-indol.vercel.app/

**Comment by alexbaumgertner** [comment]
> @alexbaumgertner 
> 
> поправила
> 
> можно смотреть
> 
> https://my-interviews-indol.vercel.app/

![image](https://github.com/AnnaApk/my-interviews/assets/223620/d0156742-bb7b-4b19-9d3d-87b1fe1d08e9)

Опыт добавляется, но в инпут не подставляется имя

**Comment by AnnaApk** [comment]
@alexbaumgertner 
поправила

**Comment by alexbaumgertner** [comment]
Все работает, спасибо большое!!!
